<?php

namespace Database\Seeders;

use App\Models\MitraPaud;
use Illuminate\Database\Seeder;

class MitraPaudSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nama_responden' => 'Dr. Bambang Sutrisno',
                'jabatan_responden' => 'Kepala Bidang PAUD',
                'telepon_responden' => '081234567890',
                'nama_organisasi' => 'Dinas Pendidikan Kota Surabaya',
                'kategori_organisasi' => 'Pemerintah',
                'alamat' => 'Jl. Jimerto No. 25-27, Surabaya',
                'telepon' => '031-5472500',
                'email' => 'dispendik@surabaya.go.id',
                'website' => 'https://dispendik.surabaya.go.id',
                'nama_pimpinan' => 'Drs. Supomo, M.Pd.',
                'tujuan_organisasi' => 'Meningkatkan kualitas pendidikan anak usia dini di Surabaya',
                'logo_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Coat_of_arms_of_Surabaya.svg/200px-Coat_of_arms_of_Surabaya.svg.png',
                'jenis_kerjasama' => ['Advokasi', 'Sosialisasi', 'Pelatihan'],
                'catatan_kerjasama' => 'Kerjasama dalam penyelenggaraan program PAUD HI',
                'dokumen_komitmen_url' => null,
                'link_pendukung' => 'https://dispendik.surabaya.go.id/paud',
                'status' => 'approved',
            ],
            [
                'nama_responden' => 'Dr. Siti Rahayu',
                'jabatan_responden' => 'Kepala Bidang Kesehatan Keluarga',
                'telepon_responden' => '081234567891',
                'nama_organisasi' => 'Dinas Kesehatan Kota Surabaya',
                'kategori_organisasi' => 'Pemerintah',
                'alamat' => 'Jl. Jemursari No. 197, Surabaya',
                'telepon' => '031-8439473',
                'email' => 'dinkes@surabaya.go.id',
                'website' => 'https://dinkes.surabaya.go.id',
                'nama_pimpinan' => 'dr. Febria Rachmanita, M.Kes.',
                'tujuan_organisasi' => 'Mewujudkan anak Surabaya yang sehat dan bebas stunting',
                'logo_url' => 'https://ui-avatars.com/api/?name=Dinkes+Surabaya&background=ef4444&color=fff&size=200',
                'jenis_kerjasama' => ['Kesehatan', 'Gizi', 'Imunisasi'],
                'catatan_kerjasama' => 'Program pencegahan stunting dan imunisasi di PAUD',
                'dokumen_komitmen_url' => null,
                'link_pendukung' => 'https://dinkes.surabaya.go.id',
                'status' => 'approved',
            ],
            [
                'nama_responden' => 'Hj. Kartini, S.E.',
                'jabatan_responden' => 'Ketua Umum',
                'telepon_responden' => '081234567892',
                'nama_organisasi' => 'HIMPAUDI Kota Surabaya',
                'kategori_organisasi' => 'Organisasi Profesi',
                'alamat' => 'Jl. Raya Darmo No. 45, Surabaya',
                'telepon' => '031-5676543',
                'email' => 'himpaudi.surabaya@gmail.com',
                'website' => 'https://himpaudi-surabaya.org',
                'nama_pimpinan' => 'Hj. Kartini, S.E.',
                'tujuan_organisasi' => 'Meningkatkan profesionalisme guru PAUD di Surabaya',
                'logo_url' => 'https://ui-avatars.com/api/?name=HIMPAUDI&background=f59e0b&color=fff&size=200',
                'jenis_kerjasama' => ['Pelatihan', 'Sertifikasi', 'Pengembangan SDM'],
                'catatan_kerjasama' => 'Pelatihan dan sertifikasi guru PAUD',
                'dokumen_komitmen_url' => null,
                'link_pendukung' => null,
                'status' => 'approved',
            ],
            [
                'nama_responden' => 'Ir. Ahmad Wijaya',
                'jabatan_responden' => 'CSR Manager',
                'telepon_responden' => '081234567893',
                'nama_organisasi' => 'PT Telkom Indonesia (Persero) Tbk',
                'kategori_organisasi' => 'Swasta/CSR',
                'alamat' => 'Jl. Ketintang No. 156, Surabaya',
                'telepon' => '031-8470000',
                'email' => 'csr.surabaya@telkom.co.id',
                'website' => 'https://www.telkom.co.id',
                'nama_pimpinan' => 'Ririek Adriansyah',
                'tujuan_organisasi' => 'Mendukung digitalisasi pendidikan anak usia dini',
                'logo_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Telkom_Indonesia_2013.svg/200px-Telkom_Indonesia_2013.svg.png',
                'jenis_kerjasama' => ['Infrastruktur Digital', 'Pelatihan IT', 'Donasi'],
                'catatan_kerjasama' => 'Program SIBUNDA dan digitalisasi PAUD',
                'dokumen_komitmen_url' => null,
                'link_pendukung' => 'https://www.telkom.co.id/csr',
                'status' => 'approved',
            ],
            [
                'nama_responden' => 'Dra. Endang Supriyati',
                'jabatan_responden' => 'Ketua TP PKK Kota Surabaya',
                'telepon_responden' => '081234567894',
                'nama_organisasi' => 'Tim Penggerak PKK Kota Surabaya',
                'kategori_organisasi' => 'Organisasi Masyarakat',
                'alamat' => 'Jl. Jimerto No. 25-27, Surabaya',
                'telepon' => '031-5312144',
                'email' => 'pkk@surabaya.go.id',
                'website' => 'https://pkk.surabaya.go.id',
                'nama_pimpinan' => 'Dra. Endang Supriyati',
                'tujuan_organisasi' => 'Pemberdayaan keluarga dalam pengasuhan anak',
                'logo_url' => 'https://ui-avatars.com/api/?name=PKK+Surabaya&background=ec4899&color=fff&size=200',
                'jenis_kerjasama' => ['Penyuluhan', 'Pendampingan Keluarga', 'Posyandu'],
                'catatan_kerjasama' => 'Program pos PAUD dan parenting',
                'dokumen_komitmen_url' => null,
                'link_pendukung' => null,
                'status' => 'approved',
            ],
            [
                'nama_responden' => 'Prof. Dr. M. Nasih, SE., MT., Ak., CMA.',
                'jabatan_responden' => 'Rektor',
                'telepon_responden' => '081234567895',
                'nama_organisasi' => 'Universitas Airlangga',
                'kategori_organisasi' => 'Perguruan Tinggi',
                'alamat' => 'Kampus C UNAIR, Mulyorejo, Surabaya',
                'telepon' => '031-5914042',
                'email' => 'info@unair.ac.id',
                'website' => 'https://www.unair.ac.id',
                'nama_pimpinan' => 'Prof. Dr. M. Nasih, SE., MT., Ak., CMA.',
                'tujuan_organisasi' => 'Penelitian dan pengembangan pendidikan anak usia dini',
                'logo_url' => 'https://upload.wikimedia.org/wikipedia/id/thumb/f/f2/Airlangga_University_logo.svg/200px-Airlangga_University_logo.svg.png',
                'jenis_kerjasama' => ['Penelitian', 'KKN Tematik', 'Pendampingan Akademik'],
                'catatan_kerjasama' => 'Kerjasama penelitian pengembangan PAUD',
                'dokumen_komitmen_url' => null,
                'link_pendukung' => 'https://fib.unair.ac.id',
                'status' => 'approved',
            ],
            [
                'nama_responden' => 'Hj. Siti Aminah',
                'jabatan_responden' => 'Ketua Forum PAUD',
                'telepon_responden' => '081234567896',
                'nama_organisasi' => 'Forum PAUD Kota Surabaya',
                'kategori_organisasi' => 'Organisasi Profesi',
                'alamat' => 'Jl. Wonokromo No. 100, Surabaya',
                'telepon' => '031-8123456',
                'email' => 'forumpaud.surabaya@gmail.com',
                'website' => null,
                'nama_pimpinan' => 'Hj. Siti Aminah',
                'tujuan_organisasi' => 'Wadah komunikasi dan koordinasi pengelola PAUD',
                'logo_url' => 'https://ui-avatars.com/api/?name=Forum+PAUD&background=6366f1&color=fff&size=200',
                'jenis_kerjasama' => ['Koordinasi', 'Advokasi', 'Pengembangan Kurikulum'],
                'catatan_kerjasama' => 'Koordinasi program PAUD se-Kota Surabaya',
                'dokumen_komitmen_url' => null,
                'link_pendukung' => null,
                'status' => 'approved',
            ],
            [
                'nama_responden' => 'dr. Wahyu Santoso, Sp.A.',
                'jabatan_responden' => 'Direktur',
                'telepon_responden' => '081234567897',
                'nama_organisasi' => 'RSUD Dr. Soewandhie',
                'kategori_organisasi' => 'Kesehatan',
                'alamat' => 'Jl. Tambak Rejo No. 45, Surabaya',
                'telepon' => '031-3716789',
                'email' => 'rsudsoewandhie@surabaya.go.id',
                'website' => 'https://rsudsoewandhie.surabaya.go.id',
                'nama_pimpinan' => 'dr. Wahyu Santoso, Sp.A.',
                'tujuan_organisasi' => 'Pelayanan kesehatan anak dan deteksi dini tumbuh kembang',
                'logo_url' => 'https://ui-avatars.com/api/?name=RSUD+Soewandhie&background=0891b2&color=fff&size=200',
                'jenis_kerjasama' => ['Pemeriksaan Kesehatan', 'Deteksi Dini', 'Imunisasi'],
                'catatan_kerjasama' => 'Pemeriksaan kesehatan berkala anak PAUD',
                'dokumen_komitmen_url' => null,
                'link_pendukung' => null,
                'status' => 'approved',
            ],
        ];

        foreach ($data as $item) {
            MitraPaud::firstOrCreate(['nama_organisasi' => $item['nama_organisasi']], $item);
        }
    }
}
